animals = {
    "elk" : "MVLSATDKSNVKAAWGKVGGNAPAYGAEALERMFLSFPTT",
    "musk_shrew" : "-VLSANDKANVKAAWDKVGGQAANYGAEALERTFASFPTT",
    "nine_banded_armadillo" : "-VLSAADKTHVKAFWGKVGGHAAEFGAEALERMFASFPPT",
    "caribou" : "-VLSAADKSNVKAAWGKVGGNAPAYGAEALERMFLSFPTT",
    "big_eared_bat" : "-VLSAADKGNVKAAWDKVGGQAGEYGAEALERMFLSFPTT",
    "cow" : "MVLSAADKGNVKAAWGKVGGHAAEYGAEALERMFLSFPTT",
    "golden_hamster" : "-VLSAKDKTNISEAWGKIGGHAGEYGAEALERMFFVYPTT",
    "mouse" : "MVLSGEDKSNIKAAWGKIGGHAGEYGAEALERMFASFPTT",
    "pallid_bat" : "MVLSPADKTNVKAAWDKVGGHAGDYGAEALERMFLSFPTT"
}


